=== i068096/Canoo-WebTest/doc/info/manual/manpage.dtd
<!ENTITY % inline 'key|em|example|n|pageref|sectionref|stepref|sidebar|ext|buildNumber|today|file|img|posted' >

<!ENTITY nbsp "&#160;">

<!-- dtd for manual pages -->
<!ELEMENT manpage (site, head,(section)+)>
<!ATTLIST manpage siteid CDATA #IMPLIED>

<!ELEMENT head (b)+>
<!ATTLIST head title CDATA #REQUIRED>

<!ELEMENT code (#PCDATA|tag|att|val|n|t|include)*>
<!ATTLIST code caption CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include src CDATA #REQUIRED>

<!ELEMENT buildNumber EMPTY>
<!ELEMENT today EMPTY>

<!ELEMENT tag (#PCDATA)>
<!ELEMENT att (#PCDATA)>
<!ELEMENT val (#PCDATA)>

<!ELEMENT n EMPTY>
<!ELEMENT t EMPTY>
<!ELEMENT file (#PCDATA)>

<!ELEMENT example (#PCDATA)*>
<!ELEMENT em (#PCDATA)*>
<!ELEMENT citeref (#PCDATA)*>
<!ELEMENT key (#PCDATA)*>
<!ELEMENT b (#PCDATA|%inline;)*>

<!ELEMENT pageref EMPTY>
<!ATTLIST pageref name CDATA #REQUIRED>

<!ELEMENT sidebar EMPTY>
<!ATTLIST sidebar name CDATA #REQUIRED>

<!ELEMENT stepref EMPTY>
<!ATTLIST stepref
    name CDATA #REQUIRED
    category CDATA #REQUIRED
    >

<!ELEMENT attributes (attribute)* >
<!ELEMENT attribute (name, description, required) >

<!ELEMENT name (#PCDATA)* >
<!ELEMENT description (#PCDATA|em|n|key|example)* >
<!ELEMENT required (#PCDATA)* >

<!ELEMENT section (b|code|citeref|attributes|dl|jira)* >
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT ext (#PCDATA|img)*>
<!ATTLIST ext
	href CDATA #REQUIRED
	base (jira) #IMPLIED
	>

<!ELEMENT jira EMPTY>
<!ATTLIST jira href CDATA #REQUIRED>

<!ELEMENT img (#PCDATA)*>
<!ATTLIST img src CDATA #REQUIRED>

<!ELEMENT occupation (#PCDATA)*>

<!ELEMENT sectionref EMPTY>
<!ATTLIST sectionref
	number CDATA ""
	title CDATA ""
	>

<!ELEMENT dl (li)+>
<!ELEMENT li (dt?,dd?)+>
<!ELEMENT dt (#PCDATA|%inline;)*>
<!ATTLIST dt
	style (frown|smile) #IMPLIED
	>
<!ELEMENT dd (#PCDATA|%inline;)*>

<!-- dtd for references.xml -->
<!ELEMENT references (ref)+>

<!ELEMENT ref ((link|note|author|cite)*)>
<!ATTLIST ref
	id ID #REQUIRED
	title CDATA ""
	type CDATA ""
	>

<!ELEMENT link EMPTY>
<!ATTLIST link href CDATA #REQUIRED>

<!ELEMENT note (#PCDATA)*>

<!ELEMENT author (occupation)*>
<!ATTLIST author
	name CDATA #REQUIRED
	firstname CDATA ""
	>

<!ELEMENT cite (#PCDATA)*>
<!ATTLIST cite id CDATA "">

<!-- dtd for site -->
<!ELEMENT site (level1)*>
<!ATTLIST site name CDATA #REQUIRED>

<!ELEMENT level1 (level2)*>
<!ATTLIST level1
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>

<!ELEMENT level2 (level3)*>
<!ATTLIST level2
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>

<!ELEMENT level3 (#PCDATA)*>
<!ATTLIST level3
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>
<!-- dtd for news -->
<!ELEMENT news (b)*>
<!ELEMENT posted (#PCDATA|%inline;)*>

=== i068096/Canoo-WebTest/doc/info/manual/buildOverview.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd"
		[
				<!ENTITY site SYSTEM "WebTestSite.xml">
				]
		>

<manpage siteid="Build Overview">

	&site;

	<head title="Build Overview">
		<b>This section contains all reports generated during the last succesfull build of WebTest.</b>
	</head>

	<section title="Contents">
		<dl>
			<li>
				<dt>
					<pageref name="Change Log"/>
				</dt>
				<dd>Keeping track of the changes on a semantical level.
					This page should enable the user to take an informed decision whether updating
					to a new build is profitable.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Unit Test Report"/>
				</dt>
				<dd>Shows the results of running the unit tests.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Self Test Report"/>
				</dt>
				<dt>
					<pageref name="Release Test Report"/>
				</dt>
				<dd>Shows the results of the latest functional selftest.
					<n/>
					Every time Canoo WebTest is rebuilt, the selftests are triggered. Selftest
					means that Canoo WebTest is used to test itself.
					<n/>
					Like all the Canoo WebTests the selftest creates an
					<key>XML</key>
					report. The
					<pageref name="Self Test Report"/>
					is one example on how this report can
					be visualized via
					<key>XSLT</key>
					. The user can adapt this to personal or
					corporate preferences.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="API Doc"/>
				</dt>
				<dd>Shows the Application Programmer's Interface as generated by javadoc.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Test Coverage"/>
				</dt>
				<dd>Displays the Canoo WebTest
					<pageref name="Test Coverage"/>
					produced with
					<key>CLOVER</key>
					.
					<n/>
					This coverage is both, the unit test coverage and the coverage achieved
					by running the selftest suite as in the
					<pageref name="Self Test Report"/>
					.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="History"/>
				</dt>
				<dd>Displays the
					<pageref name="History"/>
					of Canoo WebTest
					<pageref name="Test Coverage"/>
					and other project statistics. It is produced with
					<key>CLOVER</key>
					.
					<n/>
					The
					<pageref name="History"/>
					starts in July 2003.
				</dd>
			</li>
		</dl>
	</section>

</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/relatedProjects.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" 
[
	<!ENTITY site SYSTEM "WebTestSite.xml">
]
>

<manpage siteid="Related Projects">

	&site;

	<head title="Related projects">
		<b>Projects making WebTest use easier or extending it:</b>
	</head>

	<section title="WebTestRecorder">
		<b>
		WebTestRecorder is an open source Firefox plugin that helps working with WebTest. 
		Like WebTest it is kindly hosted by Canoo.
		</b>
		<b>
		WebTestRecorder website: <ext href="http://webtestrecorder.canoo.com">http://webtestrecorder.canoo.com</ext>
		</b>
	</section>
	
	<section title="Maven 2 WebTest plugin">
		<b>
		Integrates WebTest in Maven 2 projects
		</b>
		<b>
		Maven 2 WebTest plugin website: <ext href="http://mojo.codehaus.org/webtest-maven-plugin/">http://mojo.codehaus.org/webtest-maven-plugin/</ext>
		</b>
	</section>

	<section title="Maven 1 WebTest plugin">
		<b>
		Integrates WebTest in Maven 1 projects
		</b>
		<b>
		Maven 1 WebTest plugin website: <ext href="http://maven-plugins.sourceforge.net/maven-webtest-plugin/">http://maven-plugins.sourceforge.net/maven-webtest-plugin/</ext>
		</b>
	</section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/sources.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" 
[
	<!ENTITY site SYSTEM "WebTestSite.xml">
]
>

<manpage siteid="Sources">

	&site;

	<section title="SVN Repository">

		<b>You can connect to Canoo WebTest's public SVN via:
			<n/>
            <ext href="https://svn.canoo.com/trunk/webtest">https://svn.canoo.com/trunk/webtest</ext>
        </b>
    </section>
    
    <section title="Browse online">

		<b>
            For browsing and searching the repository online, use our
			<ext href="http://webtest.canoo.com/fisheye/">Fisheye</ext> service. It also contains an RSS feed that
            keeps you updated with every change to the repository.
		</b>
	</section>
</manpage>
