=== i068096/Canoo-WebTest/doc/info/manual/manpage.dtd
<!ENTITY % inline 'key|em|example|n|pageref|sectionref|stepref|sidebar|ext|buildNumber|today|file|img|posted' >

<!ENTITY nbsp "&#160;">

<!-- dtd for manual pages -->
<!ELEMENT manpage (site, head,(section)+)>
<!ATTLIST manpage siteid CDATA #IMPLIED>

<!ELEMENT head (b)+>
<!ATTLIST head title CDATA #REQUIRED>

<!ELEMENT code (#PCDATA|tag|att|val|n|t|include)*>
<!ATTLIST code caption CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include src CDATA #REQUIRED>

<!ELEMENT buildNumber EMPTY>
<!ELEMENT today EMPTY>

<!ELEMENT tag (#PCDATA)>
<!ELEMENT att (#PCDATA)>
<!ELEMENT val (#PCDATA)>

<!ELEMENT n EMPTY>
<!ELEMENT t EMPTY>
<!ELEMENT file (#PCDATA)>

<!ELEMENT example (#PCDATA)*>
<!ELEMENT em (#PCDATA)*>
<!ELEMENT citeref (#PCDATA)*>
<!ELEMENT key (#PCDATA)*>
<!ELEMENT b (#PCDATA|%inline;)*>

<!ELEMENT pageref EMPTY>
<!ATTLIST pageref name CDATA #REQUIRED>

<!ELEMENT sidebar EMPTY>
<!ATTLIST sidebar name CDATA #REQUIRED>

<!ELEMENT stepref EMPTY>
<!ATTLIST stepref
    name CDATA #REQUIRED
    category CDATA #REQUIRED
    >

<!ELEMENT attributes (attribute)* >
<!ELEMENT attribute (name, description, required) >

<!ELEMENT name (#PCDATA)* >
<!ELEMENT description (#PCDATA|em|n|key|example)* >
<!ELEMENT required (#PCDATA)* >

<!ELEMENT section (b|code|citeref|attributes|dl|jira)* >
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT ext (#PCDATA|img)*>
<!ATTLIST ext
	href CDATA #REQUIRED
	base (jira) #IMPLIED
	>

<!ELEMENT jira EMPTY>
<!ATTLIST jira href CDATA #REQUIRED>

<!ELEMENT img (#PCDATA)*>
<!ATTLIST img src CDATA #REQUIRED>

<!ELEMENT occupation (#PCDATA)*>

<!ELEMENT sectionref EMPTY>
<!ATTLIST sectionref
	number CDATA ""
	title CDATA ""
	>

<!ELEMENT dl (li)+>
<!ELEMENT li (dt?,dd?)+>
<!ELEMENT dt (#PCDATA|%inline;)*>
<!ATTLIST dt
	style (frown|smile) #IMPLIED
	>
<!ELEMENT dd (#PCDATA|%inline;)*>

<!-- dtd for references.xml -->
<!ELEMENT references (ref)+>

<!ELEMENT ref ((link|note|author|cite)*)>
<!ATTLIST ref
	id ID #REQUIRED
	title CDATA ""
	type CDATA ""
	>

<!ELEMENT link EMPTY>
<!ATTLIST link href CDATA #REQUIRED>

<!ELEMENT note (#PCDATA)*>

<!ELEMENT author (occupation)*>
<!ATTLIST author
	name CDATA #REQUIRED
	firstname CDATA ""
	>

<!ELEMENT cite (#PCDATA)*>
<!ATTLIST cite id CDATA "">

<!-- dtd for site -->
<!ELEMENT site (level1)*>
<!ATTLIST site name CDATA #REQUIRED>

<!ELEMENT level1 (level2)*>
<!ATTLIST level1
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>

<!ELEMENT level2 (level3)*>
<!ATTLIST level2
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>

<!ELEMENT level3 (#PCDATA)*>
<!ATTLIST level3
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>
<!-- dtd for news -->
<!ELEMENT news (b)*>
<!ELEMENT posted (#PCDATA|%inline;)*>

=== i068096/Canoo-WebTest/doc/info/manual/properties.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd"
        [
                <!ENTITY site SYSTEM "WebTestSite.xml">
                ]
        >

<manpage siteid="Properties">

    &site;

    <head title="Properties">
        <b>WebTest knows about two kinds of properties, <em>ant</em> properties and
            <em>dynamic</em> properties. You typically select which kind you want to
            store into using the <em>propertyType</em> attribute
            of the storeXXX steps or by setting a <em>defaultpropertytype</em>
            in your <stepref name="config" category="general"/>.
            You select which kind you want to read from using the
            <em>${}</em> or <em>#{}</em> syntax.
            This section explains additional details about these
            two kinds of properties.
        </b>
    </head>
    <section title="Ant Properties">
        <b>${} properties are normal
            <key>ANT</key> properties. Given
            <key>ANT</key>'s philosophy
            of a declarative build process, these are normally immutable.
            I.e. once you set a property its value normally can't be changed.
            <key>ANT</key> property values are typically determined at the start of an
            ant target. They are available to both
            <key>ANT</key> tasks and WebTest steps.</b>
    </section>
    <section title="Dynamic Properties">
        <b>
            #{} properties are only available (currently) to webtest steps.
            They are dynamic - you can use the same property and set it to
            different things throughout your tests. #{} properties support
            very simple expressions and there is support for accessing
            scripting variables under special circumstances. Property values
            are determined at the moment of use.
        </b>
    </section>
    <section title="Nested Properties Expansion">
        <b>
            Contrary to normal Ant execution 
            (see <ext href="http://issues.apache.org/bugzilla/show_bug.cgi?id=29347">Ant's enhancement issue</ext>), 
            nested properties are evaluated during the execution of a WebTest.
            This means for instance that something like <em>${myProp#{counter}}</em> will be evaluated 
            just like <em>${myProp1}</em> if the current value of the dynamic property <em>counter</em> is <em>1</em>.
            Both nested Ant properties and dynamic properties are evaluated.
        </b>
    </section>
    <section title="Converting Properties">
        <b>You can happily swap between them using
            <stepref name="storeProperty" category='Core'/>
            by setting the <em>propertyType</em>
            attribute to the appropriate value.
        </b>

        <code caption="Examples showing property type conversion">
            <include src='examples/propertySwap.xml'/>
        </code>

    </section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/Downloads.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd"
        [
                <!ENTITY site SYSTEM "WebTestSite.xml">
                ]
        >
<manpage siteid="Downloads">

    &site;

    <head title="Canoo WebTest Downloads">
        <b>This page contains links to the artefacts for the latest Canoo WebTest version, as well as for
previous releases.</b></head>

    <section title="Latest Snapshot">

        <b>Release class = development, build number = <buildNumber/></b>

        <b>This latest snapshot represents the current stream of development.</b>

        <b>All releases contain the same set of files. That is:</b>
        <dl>
            <li>
                <dt>
                    <file>build.zip</file>
                </dt>
                <dd>
                    The latest build. Everything you need for running Canoo WebTest.
                </dd>
            </li>
            <li>
                <dt>
                    <file>doc.zip</file>
                </dt>
                <dd>
                    The comprehensive documentation, including the Canoo WebTest selftests. The selftests also serve as
                    a convenient template
                    for your own setup. You can reuse the directory structure, the separation
                    of concerns and the generated WebTest.DTD.
                </dd>
            </li>
            <li>
                <dt>
                    <file>src.zip</file>
                </dt>
                <dd>
                    The java source files that make up the Canoo WebTest
                    <key>ANT</key>
                    tasks.<n/>
                    Note that you should consult <pageref name="Building"/> if you want to build WebTest.
                </dd>
            </li>
            <li>
                <dt>
                    <file>selftest.war</file>
                </dt>
                <dd>
                    The Web Application that
                    Canoo WebTest uses to test itself.
                </dd>
            </li>
            <li>
                <dt>
                    <file>build-maven.zip</file>
                </dt>
                <dd>
                    The latest build in maven format.
                </dd>
            </li>
        </dl>
    </section>

    <section title="WebTest 3.0">

        <b>The 3.0 Release consolidates all changes to Canoo WebTest since release 2.6 (see
        <ext href="http://webtest-community.canoo.com/jira/browse/WT?report=com.atlassian.jira.plugin.system.project:changelog-panel">Change log</ext>)
        </b>
        <b>This is the recommended version of WebTest for beginners. Existing users are also encouraged to upgrade.
        It offers many improvements over release 2.6 (bug fixes, speed improvements, better javascript support, ...)
        </b>
        <b>Contrary to earlier releases, release 3.0 requires Java 5.</b>
        <b><em>Warning:</em> possible changes in XPath usage<n/>
        Starting with build 1700, the HtmlUnit version used by WebTest has been upgraded to the latest 2.x release,
        which doesn't use Jaxen anymore for XPath evaluation with a custom document navigator but standard DOM tools.
        The consequence is that XPath expressions
        now have to be "fully correct" and can't use shortcuts that were previously available.
        For example an expression like "//tr[td='2.1']/td[3]" won't work
        anymore and should be replaced with something like "//tr[td/text() = '2.1']/td[3]".
        Additionally, spaces are no longer trimmed to respect XPath standards
        (the function wt:cleanText can be used to ignore whitespaces).
		</b>

        <b>The release has the tag R_1758 in the repository.</b>

        <b>Refer to
            <ext href="https://svn.canoo.com/trunk/webtest-releases/3.0-1758">Download Release 3.0</ext>
            Read the <em>readme.txt</em> and <em>releaseNotes.txt</em> for details.
        </b>
    </section>

    <section title="WebTest 2.6">

        <b>The 2.6 Release consolidates all changes to Canoo WebTest since release 2.5 (see 
        <ext href="http://webtest-community.canoo.com/jira/browse/WT?report=com.atlassian.jira.plugin.system.project:changelog-panel">Change log</ext>)
        </b>
        <b>This is the latest version that targets Java 1.4.</b>
        <b>The release has the tag R_1689 in the repository.</b>

        <b>Refer to
            <ext href="https://svn.canoo.com/trunk/webtest-releases/2.6-1689">Download Release 2.6</ext>
            Read the <em>readme.txt</em> and <em>releaseNotes.txt</em> for details.
        </b>
    </section>

    <section title="WebTest 2.5">

        <b>The 2.5 Release consolidates all changes to Canoo WebTest since release 2.1 (see 
        <ext href="http://webtest-community.canoo.com/jira/browse/WT?report=com.atlassian.jira.plugin.system.project:changelog-panel">Change log</ext>)
        </b>
        <b>The release has the tag R_1551 in the repository.</b>

        <b>Refer to
            <ext href="https://svn.canoo.com/trunk/webtest-releases/2.5-1551">Download Release 2.5</ext>
            Read the <em>readme.txt</em> for details.
        </b>
    </section>

    <section title="WebTest 2.1">

        <b>The 2.1 Release consolidates all changes to Canoo WebTest since release 2.0.</b>
        <b>The release has the tag R_1393 in the repository.</b>

        <b>Refer to
            <ext href="https://svn.canoo.com/trunk/webtest-releases/2.1-1393">Download Release 2.1</ext>
            .
            Read the
            <em>readme.txt</em>
            for details.
        </b>

    </section>
    <section title="WebTest 2.0">

        <b>The 2.0 Release is the first release of Canoo WebTest that is based on HtmlUnit.
            It builds upon HtmlUnit version 1.8.
        </b>
        <b>The release has the tag R_1217 in the repository.</b>

        <b>Refer to
            <ext href="https://svn.canoo.com/trunk/webtest-releases/2.0-1217">Download Release 2.0</ext>
            .
            Read the
            <em>readme.txt</em>
            for details.
        </b>

    </section>
    <section title="WebTest 1.6">

        <b>The 1.6 Release is the last Release of Canoo WebTest that is based on HttpUnit.
            It builds upon HttpUnit version 1.6.</b>
        <b>The release has the tag R_544 in the repository.</b>

        <b>Refer to
            <ext href="https://svn.canoo.com/trunk/webtest-releases/1.6-544">Download Release 1.6</ext>
            .
            Read the
            <em>readme.txt</em>
            for details.
        </b>


    </section>
    <section title="WebTest 1.5">

        <b>The 1.5 Release is based on HttpUnit 1.5.4.</b>
        <b>The release has the tag R_535 in the repository.</b>
        <b>If you have any compatibility issues with your own custom steps or with contributions
            from the community site, this release may be what you are looking for.
        </b>

        <b>Refer to
            <ext href="https://svn.canoo.com/trunk/webtest-releases/1.5-535">Download Release 1.5</ext>
            .
            Read the
            <em>readme.txt</em>
            for details.
        </b>
    </section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/license.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" 
[
	<!ENTITY site SYSTEM "WebTestSite.xml">
]
>

<manpage siteid="License"> 

&site;  
 
<head title="Canoo WebTest">

</head>

<section title="Software License">

<b>
 Copyright 2002-2008 Canoo Engineering AG, Basel, Switzerland<n/>
 <n/>
 Licensed under the Apache License, Version 2.0 (the "License").<n/>
 <n/>
 You may obtain a copy of the License at<n/>
  <ext href="http://www.apache.org/licenses/LICENSE-2.0">http://www.apache.org/licenses/LICENSE-2.0</ext>
</b>

<b>  
 Unless required by applicable law or agreed to in writing, software distributed under the License
 is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express 
 or implied. See the License for the specific language governing permissions and limitations under the License. 
</b>

</section>

</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/manualOverview.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd"
		[
				<!ENTITY site SYSTEM "WebTestSite.xml">
				]
		>

<manpage siteid="Manual Overview">

	&site;

	<head title="Manual Overview">
		<b>This section provides extensive documentation on the use of WebTest.</b>
	</head>

	<section title="Contents">
		<dl>
			<li>
				<dt>
					<pageref name="Samples"/>
				</dt>
				<dd>An introduction to webtest.
					This page show the stepwise development of a first test suite.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Properties"/>
				</dt>
				<dd>Introduction to webtest property types.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Syntax Reference - Core Steps"/>
				</dt>
				<dd>Reference pages for the steps. The core steps are all the basic steps of webetest.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Syntax Reference - Extension Steps"/>
				</dt>
				<dd>Reference pages for the extension steps. Extension steps are part of the distribution,
					but have been less heavily used and are less well documented than the Core steps
					and are also more likely to change.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Syntax Reference - Filter Steps"/>
				</dt>
				<dd>Reference pages for the filter steps. Filter steps allow the content of web responses
					to be manipulated (or
					<em>filtered</em>
					) for the purposes of making the response
					content more suitable for testing purposes. Filter steps are part of the distribution,
					but have been less heavily used and are less well documented than the Core steps
					and are also more likely to change.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Syntax Reference - PDF Steps"/>
				</dt>
				<dd>Reference pages for the PDF steps that let webtest verify the
					content and properties of PDF documents.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Syntax Reference - Excel Steps"/>
				</dt>
				<dd>Reference pages for the Excel steps that let webtest verify the
					content and properties of XLS documents.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Syntax Reference - Email Steps"/>
				</dt>
				<dd>Reference pages for the Email steps that let webtest verify the
					content and properties of Email messages and Email attachments.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Step Index"/>
				</dt>
				<dd>An alphabetical index to all the steps.
				</dd>
			</li>
			<li>
				<dt>
					<pageref name="Groovy Testing"/>
				</dt>
				<dd>Tutorial page to show how to use Canoo WebTest trough Groovy.</dd>
			</li>
		</dl>
	</section>

	<section title="Further Resources">
		<b>The page
			<sidebar name="sidebar"/>
			is a simple index of all steps. It can be used as a sidebar!
			Installation in Firefox and Opera should be automatic, please consult your browser's documentation for
			installation on other browsers.
		</b>
	</section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/keyCharacteristics.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd"
[
	<!ENTITY site       SYSTEM "WebTestSite.xml">
]
>

<manpage siteid="Key Characteristics">

	&site;

	<head title="WebTest Key Characteristics">

		<b>Here is a short overview of WebTest characteristics</b>

	</head>

	<section title="Pros">
		<dl>
			<li>
				<dt style="smile">Simple</dt>
			</li>
			<li>
				<dt style="smile">Fast</dt>
			</li>
			<li>
				<dt style="smile">Excellent Reporting</dt>
			</li>
			<li>
				<dt style="smile">Very low TCO</dt>
			</li>
			<li>
				<dt style="smile">Runs everywhere</dt>
			</li>
			<li>
				<dt style="smile">No display needed</dt>
			</li>
			<li>
				<dt style="smile">Easy to extend</dt>
			</li>
			<li>
				<dt style="smile">Straightforward integration</dt>
			</li>
			<li>
				<dt style="smile">Doesn't accept (too) badly formed html</dt>
			</li>
		</dl>
	</section>

	<section title="Cons">
		<dl>
			<li>
				<dt style="frown">Javascript support not as good as in "normal" browser</dt>
			</li>
			<li>
				<dt style="frown">Doesn't accept (too) badly formed html</dt>
			</li>
		</dl>
	</section>

	<section title="Explanations">
		<dl>
			<li>
				<dt>Simple</dt>
				<dd>WebTest has an easy syntax with steps having meaningful names that can be understood even when you don't know WebTest.
				Additionally, the recorder allows you to quickly generate a first draft of your tests that you can adapt and refactor 
				to build robust tests suites.
				Don't forget: capture/replay is the least cost-effective way of automating test cases! </dd>
			</li>
			<li>
				<dt>Fast</dt>
				<dd>WebTest doesn't download CSS or images and doesn't need to compute page rendering.</dd>
			</li>
			<li>
				<dt>Excellent Reporting</dt>
				<dd>Perhaps the most important feature. 
				JUnit like reports are not enough to understand why a test fails and WebTest reports provide all information allowing you to quickly understand the failure cause.</dd>
			</li>
			<li>
				<dt>Very low TCO</dt>
				<dd>Some user testimonials say it better than long explanations: 
				"the ROI on WebTest is many orders of magnitude higher than any other tool I've used",
				"Support = good and $0", 
				"It still Just Works", 
				"It has been remarkably robust, mature, and bug-free", 
				or "tests are much quicker to write and cheap to maintain".
				</dd>
			</li>
			<li>
				<dt>Runs everywhere</dt>
				<dd>WebTest is plain Java and runs everywhere as long as you have a JDK for your operating system.</dd>
			</li>
			<li>
				<dt>No display needed</dt>
				<dd>This means that you can continue working on your computer while your test(s) run.</dd>
			</li>
			<li>
				<dt>Easy to extend</dt>
				<dd>
				No matter which tool you use, you will reach its limits and need to extend it for your custom needs. It's only a question of time. 
				With WebTest you can simply create your own steps without technology mix, exactly like WebTest's own steps in Java or in Groovy
				and access the whole API of HtmlUnit, commons-httpclient, ... to enhance WebTest for your special requirements.
				</dd>
			</li>
			<li>
				<dt>Straightforward integration</dt>
				<dd>
				WebTest scripts ARE Ant scripts. This means that you have directly an easy integration in continuous integration tools like Cruise Control,
				support in your favorite IDE, ...
				</dd>
			</li>
			<li>
				<dt>Doesn't accept (too) badly formed html</dt>
				<dd>
				"Real" browsers accept really badly formed html code what WebTest can only do to some extend. Good or bad? 
				We (the WebTest developers) want to create correct web applications and we see this as a feature rather than as a disadvantage.
				After all, testing should lead to better quality.
				</dd>
			</li>
			<li>
				<dt>Javascript support not as good as in "normal" browser</dt>
				<dd>
				WebTest simulates Firefox' or Internet Explorer's way to execute JavaScript. This behavior is simulated, which means that it 
				doesn't work as good as in "real" browser. So, how bad is it? Not that bad at all, even complex js libraries like DWR or Google Maps already 
				work and development in HtmlUnit (the underlying browser) progresses rapidly with the upcoming release supporting Prototype, GWT, etc.
				</dd>
			</li>
		</dl>
	</section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/building.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" [ <!ENTITY site SYSTEM "WebTestSite.xml"> ] >
<manpage siteid="Building">

	&site;

	<head title="Building WebTest">
		<b>This page describes how to build webtest from the sources.
			The build file included with the source provides a complete and repeatable build process, which the second
			section explains.
			The build file is used by the build server to produces high quality deliveries but can, and should, also be
			used to
			develop WebTest. It is however convenient during development to build webtest from the comfort of an IDE,
			and the third section gives a few hints on ow to set-up an IDE.
		</b>
	</head>

	<section title="Prerequisites">
		<dl>
			<li>
				<dt>A platform that is able to run Java.</dt>
			</li>
			<li>
				<dt>An installed JDK version 6 or higher.</dt>
			</li>
			<li>
				<dt>Ant, version 1.8.4 or newer.</dt>
				<dd>The distributions of webtest contain the necessary part from ant 1.8.4 ready to run.</dd>
			</li>
		</dl>
	</section>


	<section title="Building WebTest with ant">

		<b>Rebuilding the whole Canoo WebTest from the source may be
			an option if you want to change it's behavior.
		</b>

		<b>First, checkout the latest version from the svn repository to
			<example>&lt;WEBTEST_HOME&gt;</example>
			:
		</b>
		<code>svn co https://svn.canoo.com/trunk/webtest</code>
		<b>Then call the build script. Depending from your operating system, it may be necessary to fiddle
			with the execution rights of the scripts in the directory
			<example>bin/</example>
			.
		</b>
		<b>The main build file in
			<example>&lt;WEBTEST_HOME&gt;</example>
			provides the following targets:
		</b>
		<dl>
			<li>
				<dt>clean</dt>
				<dd>Deletes (most of) the results of a previous build.</dd>
			</li>
			<li>
				<dt>develop</dt>
				<dd>Compiles and tests webtest.</dd>
			</li>
			<li>
				<dt>full</dt>
				<dd>Compiles and tests webtest, then generates all kinds of documentations and reports.
					<n/>
					This is the target used by the build server.
				</dd>
			</li>
			<li>
				<dt>fetchDependencies</dt>
				<dd>Lets maven fetch all the dependencies described in the pom.
					This target needs only to be called explicitly if the build will occur offline.
				</dd>
			</li>
		</dl>
		<b>To generate a complete release, including the documentation, type:</b>
		<code>
			cd &lt;WEBTEST_HOME&gt;
			<n/>
			bin/webtest.sh full
		</code>
		<b>To get a clean build without documentation, type:</b>
		<code>
			cd &lt;WEBTEST_HOME&gt;
			<n/>
			bin/webtest clean develop
		</code>
	</section>
	<section title="Building with an IDE">
		<b>As there are too many possible IDEs, this section only outlines how to set-up an IDE.</b>
		<b>Although webtest build is an ant script, it is taking advantage of
			<key>Maven</key>
			's (version 2) declarative
			definition of dependencies: All dependencies required to build and run webtest are defined in the file
			<em>pom.xml</em>
			. The target
			<em>fetchDependencies</em>
			of the build script looks at the required dependencies, looks at maven's dependency cache (in the user's
			home directory) and downloads the dependency jar files from one of the
			maven repositories to the shared dependency cache.
		</b>
		<b>Since the actual dependency jar files are not part of the module, but potentially shared with other unrelated
			projects, the difficulty is to tell the IDE which jar files it needs and where they are. The easiest
			solution is to take advantage of maven's various plugins to convert webtest's
			<em>pom.xml</em>
			to a project file for an IDE. This requires of course maven (version 2!) to be available on the machine.
		</b>
		<b>Note that some dependencies are indeed part of webtest's module: these are jar files for versions that are
			not (yet?) available on a public maven repository. These jar files are however organized as a local maven
			repository and accessed like every other dependencies.
		</b>
	</section>
	<section title="IntelliJ IDEA">
		<b>To create an
			<em>Idea project</em>, just use:
		</b>
		<code>
			cd &lt;WEBTEST_HOME&gt;
			<n/>
			mvn idea:idea
		</code>
	</section>
	<section title="Eclipse">
		<b>To create an
			<em>eclipse project</em>, just use:
		</b>
		<code>
			cd &lt;WEBTEST_HOME&gt;
			<n/>
			mvn eclipse:eclipse
		</code>
		<b>Note that working with the generated project-files in eclipse requires to define a new classpath
			variable named
			<em>M2_REPO</em>
			which leads to your local maven repository. It must be defined under
			<example>preferences -&gt; java -&gt; build path</example>
			.
		</b>
	</section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/changeLog.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" [
		<!ENTITY site SYSTEM "WebTestSite.xml">
		]>
<manpage siteid="Change Log">

	&site;

	<head title="Change Log">
		<b>The most up-to-date list of changes is kept in
			<key>Jira</key>
			, our bug tracking system. The
			<ext
					href="browse/WT?report=com.atlassian.jira.plugin.system.project:roadmap-panel"
					base="jira"
					>Road-Map
			</ext>
			lists all the important changes since the last release.
		</b>
	</head>

	<section title="Change Log">
		<b>All tickets closed at the time of build
			<buildNumber/>
			are:
		</b>
		<!--
				The value of the parameter fixfor must be changed by hand when new release are marked in jira.
				10061 is "future work".
				The href is jira's rss feed from the 'Road Map' of the desired version.
				
				Gets 300 'closed', 'fixed' items, sorted by issue number.
				Lets jira sort the issues, it does it besser than xsl can do.
				-->
		<!--<jira href="secure/IssueNavigator.jspa?view=rss&amp;pid=10000&amp;fixfor=10021&amp;reset=true&amp;decorator=none&amp;tempMax=300&amp;resolution=1&amp;status=6&amp;sorter/field=issuekey&amp;sorter/order=ASC"/>-->
		<jira href="secure/IssueNavigator.jspa?view=rss&amp;pid=10000&amp;resolution=1&amp;fixfor=10061&amp;status=6&amp;sorter/field=issuekey&amp;sorter/order=ASC&amp;sorter/field=updated&amp;sorter/order=DESC&amp;tempMax=25&amp;reset=true&amp;decorator=none"/>
	</section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/_news.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE news SYSTEM "manpage.dtd">

<news>
	<b>Latest build:
		<buildNumber/>
		<posted>
			<today/>
		</posted>
	</b>
	<b>
		WebTest 3.0 released, featuring upgrades to Java 5, Groovy 1.6, and
		HtmlUnit 2.4. <n/>
		The release includes support for maven integration, IDE-integration
        like for unit tests, capturing of background JavaScript errors, new steps
        for mouseOver and mouseOut events, better parallel execution of tests
		and - as usual - lots of handling improvements.

		<posted>5 March 2009</posted>
	</b>
	<b>
		WebTest @ JavaOne<n/>
		Dierk König presented "Functional testing of web applications:
scaling with Java" on Wed May 7, 13:30 at <ext href="http://java.sun.com/javaone/sf/index.jsp">JavaOne 2008</ext> in the Tools and Scripting
Languages track.
		<posted>8 May 2008</posted>
	</b>
	<b>
		New WebTest screencast available:<n/>
		<ext href="http://opensource.basehaus.com/webtest/screencasts/data-driven-webtest.htm">Data Driven WebTest</ext>
		<posted>13 November 2007</posted>
	</b>
	<b>
		First WebTest screencast available:<n/>
		<ext href="http://opensource.basehaus.com/webtest/screencasts/creating-a-first-webtest-project.htm">Creating a first Webtest Project</ext>
	</b>
	<b>
		Extend WebTest with Groovy!
		<ext href="http://groovy.canoo.com/gina">Groovy in Action</ext>
		is available in every good bookstore.
		<n/>
		<ext href="http://groovy.canoo.com/gina">
			<img src="images/gina.jpg">Groovy in Action</img>
		</ext>
		<posted>29 January 2007</posted>
	</b>
</news>
