=== i068096/Canoo-WebTest/doc/info/manual/manpage.dtd
<!ENTITY % inline 'key|em|example|n|pageref|sectionref|stepref|sidebar|ext|buildNumber|today|file|img|posted' >

<!ENTITY nbsp "&#160;">

<!-- dtd for manual pages -->
<!ELEMENT manpage (site, head,(section)+)>
<!ATTLIST manpage siteid CDATA #IMPLIED>

<!ELEMENT head (b)+>
<!ATTLIST head title CDATA #REQUIRED>

<!ELEMENT code (#PCDATA|tag|att|val|n|t|include)*>
<!ATTLIST code caption CDATA #IMPLIED>

<!ELEMENT include EMPTY>
<!ATTLIST include src CDATA #REQUIRED>

<!ELEMENT buildNumber EMPTY>
<!ELEMENT today EMPTY>

<!ELEMENT tag (#PCDATA)>
<!ELEMENT att (#PCDATA)>
<!ELEMENT val (#PCDATA)>

<!ELEMENT n EMPTY>
<!ELEMENT t EMPTY>
<!ELEMENT file (#PCDATA)>

<!ELEMENT example (#PCDATA)*>
<!ELEMENT em (#PCDATA)*>
<!ELEMENT citeref (#PCDATA)*>
<!ELEMENT key (#PCDATA)*>
<!ELEMENT b (#PCDATA|%inline;)*>

<!ELEMENT pageref EMPTY>
<!ATTLIST pageref name CDATA #REQUIRED>

<!ELEMENT sidebar EMPTY>
<!ATTLIST sidebar name CDATA #REQUIRED>

<!ELEMENT stepref EMPTY>
<!ATTLIST stepref
    name CDATA #REQUIRED
    category CDATA #REQUIRED
    >

<!ELEMENT attributes (attribute)* >
<!ELEMENT attribute (name, description, required) >

<!ELEMENT name (#PCDATA)* >
<!ELEMENT description (#PCDATA|em|n|key|example)* >
<!ELEMENT required (#PCDATA)* >

<!ELEMENT section (b|code|citeref|attributes|dl|jira)* >
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT ext (#PCDATA|img)*>
<!ATTLIST ext
	href CDATA #REQUIRED
	base (jira) #IMPLIED
	>

<!ELEMENT jira EMPTY>
<!ATTLIST jira href CDATA #REQUIRED>

<!ELEMENT img (#PCDATA)*>
<!ATTLIST img src CDATA #REQUIRED>

<!ELEMENT occupation (#PCDATA)*>

<!ELEMENT sectionref EMPTY>
<!ATTLIST sectionref
	number CDATA ""
	title CDATA ""
	>

<!ELEMENT dl (li)+>
<!ELEMENT li (dt?,dd?)+>
<!ELEMENT dt (#PCDATA|%inline;)*>
<!ATTLIST dt
	style (frown|smile) #IMPLIED
	>
<!ELEMENT dd (#PCDATA|%inline;)*>

<!-- dtd for references.xml -->
<!ELEMENT references (ref)+>

<!ELEMENT ref ((link|note|author|cite)*)>
<!ATTLIST ref
	id ID #REQUIRED
	title CDATA ""
	type CDATA ""
	>

<!ELEMENT link EMPTY>
<!ATTLIST link href CDATA #REQUIRED>

<!ELEMENT note (#PCDATA)*>

<!ELEMENT author (occupation)*>
<!ATTLIST author
	name CDATA #REQUIRED
	firstname CDATA ""
	>

<!ELEMENT cite (#PCDATA)*>
<!ATTLIST cite id CDATA "">

<!-- dtd for site -->
<!ELEMENT site (level1)*>
<!ATTLIST site name CDATA #REQUIRED>

<!ELEMENT level1 (level2)*>
<!ATTLIST level1
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>

<!ELEMENT level2 (level3)*>
<!ATTLIST level2
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>

<!ELEMENT level3 (#PCDATA)*>
<!ATTLIST level3
	name CDATA #REQUIRED
	url CDATA #REQUIRED
	>
<!-- dtd for news -->
<!ELEMENT news (b)*>
<!ELEMENT posted (#PCDATA|%inline;)*>

=== i068096/Canoo-WebTest/doc/info/manual/sqlunit.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" [
        <!ENTITY site SYSTEM "WebTestSite.xml">
        ]>

<manpage siteid="SQLUnit Integration">

    &site;

    <head title="SQLUnit Integration">
        <b>
            <key>sqlunit</key>
            is a technology for testing databases. It can be used for testing stored procedures
            within a database or if you have a data-driven website, it can be used in conjunction
            with WebTest to ensure that the web and database parts of the application are working well together.
        </b>

        <b>Here are some sample scenarios where
            <key>sqlunit</key>
            may be useful for your WebTest-tested applications:
        </b>

        <dl>
            <li>
                <dt>Integration Test Pre-condition Checking</dt>
                <dd>You might be about to call a WebTest test
                    which assumes a particular user is already valid within your system. <key>sqlunit</key> could help
                    you check a precondition such as the user exists and is not disabled.</dd>
            </li>
            <li>
                <dt>Integration Test Post-condition Checking</dt>
                <dd>You can check integration between your web application and your
                    model. E.g. create a new user using a form driven via WebTest and then
                    check that the newly created user now exists in the database.</dd>
            </li>
            <li>
                <dt>Database Data Manipulation and/or Cleanup</dt>
                <dd>You may wish to run some tests using temporary data. You could create a user
                    using <key>sqlunit</key>, run your WebTest steps, then remove the user again with <key>sqlunit</key>.</dd>
            </li>
        </dl>

        <b>
            <key>sqlunit</key>
            supports several reporting formats including an XML format compatible
            with WebTest's reporting format, so you can happily mix the two tools and generate combined
            reporting.
        </b>

        <b>Here is an example of how you might invoke the <key>sqlunit</key> selftests (using WebTest formatting) from the command-line:</b>

        <code caption='SQLUnit Command-line example'>
        ant sqlunit-nested canoo2html -Dtestdir=mock -Dlog.format=canoo -Doutput.file=results.xml -Dwebtest.style=WebTestReport
        </code>

        <b>Here is an example of what the resulting report might look like:</b>

        <b><img src="images/sqlunit.jpg"/></b>

        <b>Here is an example of how you might use the <key>sqlunit</key> ant task from within your WebTest file:</b>

        <code caption='SQLUnit Ant Task example'>
            <include src='integrationexamples/sqlunitAntExample.xml'/>
        </code>

        <b>Here is an example of what your <key>sqlunit</key> test file might look like:</b>

        <code caption='SQLUnit Ant Task example'>
            <include src='integrationexamples/sqlunitTest.xml'/>
        </code>

    </head>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/externalCitations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" 
[
	<!ENTITY site SYSTEM "WebTestSite.xml">
]
>

<manpage siteid="External Citations">

	&site;

	<head title="External Citations">
		<b>They are talking about WebTest:</b>
	</head>

	<section title="Upcoming Conferences">
		<dl>
		</dl>
	</section>

	<section title="Articles">
		<dl>
			<li>
				<dt>
					<ext href="http://www.sigs-datacom.de/sd/publications/pub_article_show.htm?&amp;AID=2365&amp;Table=sd_article">Funktionales Testen von Rich Internet Applications</ext>
					(German)
				</dt>
				<dd>by Michael Hüttermann</dd>
				<dd>
					<ext href="http://www.sigs-datacom.de/sd/publications/js/2008/05/index.htm">JavaSpektrum 05/2008</ext>
				</dd>
			</li>

			<li>
				<dt>
					<ext href="http://www.inet.sk/clanok/5846/testovanie-webovych-aplikacii-pouzitim-canoo-webtest-cast-i/">Testovanie webových aplikácií použitím Canoo Webtest</ext>
					(Slovak)
				</dt>
				<dd>by Roman Hesteric, 06.05.2008</dd>
			</li>
		
			<li>
				<dt>
					<ext href="http://www.heise.de/kiosk/archiv/ix/2005/12/152">Champion unter Surfern</ext>
					(German)
				</dt>
				<dd>by Benjamin Feiermann &amp; Marc Guillemot</dd>
				<dd>
					<ext href="http://www.heise.de/kiosk/archiv/ix/2005/12">iX 12/2005</ext>
					p152
				</dd>
				<dd>
					<ext href="http://www.heise.de/kiosk/special/ix/07/01">iX Special 01/2007</ext>
					p92
				</dd>
			</li>

			<li>
				<dt>
					<ext href="http://www.stickyminds.com/BetterSoftware/magazine.asp?fn=bisns&amp;ci=70">
						A Look at Canoo WebTest
					</ext>
				</dt>
				<dd>by Lisa Crispin</dd>
				<dd>Better Software Magazine, November-December 2005</dd>
			</li>

			<li>
				<dt>
					<ext href="http://www.heise.de/kiosk/archiv/ix/2002/10/88">
						Sklaventreiber - Automatische Akzeptanztests auf XML-Basis
					</ext>
					(German)
				</dt>
				<dd>by Dierk König</dd>
				<dd>
					<ext href="http://www.heise.de/kiosk/archiv/ix/2002/10">iX 10/2002</ext>
					p88
				</dd>
			</li>
		</dl>



	</section>

	<section title="Past Conferences">
		<dl>
			<li>
				<dt>
					24.04.2008:
					<ext href="http://it-republik.de/jaxenter/jax/sessions.php?tid=687#session-11">
						Nachhaltiges Testen von Web-Applikationen
					</ext>
					(German) 
				</dt>
				<dd>by Dierk König &amp; Marc Guillemot</dd>
				<dd>
					<ext href="http://www.jax.de">
						JAX 2008
					</ext>
					Wiesbaden (Germany)
				</dd>
				<dd>
				<ext href="externalCitations/WebTest@JAX08.pdf">Presentation<img src="images/pdficon_small.gif"/></ext> (mostly in English)
				</dd>
			</li>
			<li>
				<dt>
					17.10.2007:
					<ext href="http://www.grails-exchange.com/dierk-koenig#canoo-web-test">
						Canoo Web Test and Grails
					</ext>
				</dt>
				<dd>by Dierk König</dd>
				<dd>
					<ext href="http://skillsmatter.com/menu/372">
						Grails eXchange 2007
					</ext>
					London
				</dd>
			</li>
			<li>
				<dt>
					30.10.2007:
					<ext href="http://verifyconference.com/content/view/133/41/">
						Jumpstart Your Functional Test Automation with Canoo WebTest
					</ext>
				</dt>
				<dd>by Nate Oster</dd>
				<dd>
					<ext href="http://verifyconference.com/">Verify 2007</ext>
					Washington, D.C.
				</dd>
			</li>
			<li>
				<dt>
					26.09.2007:
					<ext href="http://www.kruchten.org/agilevancouver/conference_files/oster.html">
						Patterns for Continuous Functional Testing
					</ext>
				</dt>
				<dd>by Nate Oster</dd>
				<dd>
					<ext href="http://www.kruchten.org/agilevancouver/conference.html">
						Much Ado About Agile 2007
					</ext>
					Vancouver, BC
				</dd>
				<dd>
				<ext href="externalCitations/AgileVancouver2007_PatternsForContinuousTestAutomation.pdf">Presentation<img src="images/pdficon_small.gif"/></ext>
				</dd>
			</li>
			<li>
				<dt>
					26.04.2007:
					<ext href="http://jax.de/konferenzen/jax07/overview_sessions.php?track=3&amp;_language=de#session-wa7">
						Automatisiertes Testen von Webapplikationen
					</ext>
					(German) 
				</dt>
				<dd>by Dierk König &amp; Marc Guillemot</dd>
				<dd>
					<ext href="http://www.jax.de">
						JAX 2007
					</ext>
					Wiesbaden (Germany)
				</dd>
				<dd>
				<ext href="externalCitations/JAX2007_WebTestPresentation.pdf">Presentation<img src="images/pdficon_small.gif"/></ext> (mostly in English)
				</dd>
			</li>
			<li>
				<dt>
					30.11.2006:
					<ext href="http://www.ix-konferenz.de/showabstract.php?vid=811&amp;stylesheet=style/konf0502.php">
						Tutorial: Automatisiertes Testen von Web-Applikationen
					</ext>
					(German) 
				</dt>
				<dd>by Marc Guillemot &amp; Dierk König</dd>
				<dd>
					<ext href="http://www.ix-konferenz.de/einstieg.php?konferenzid=11">
						Bessere Software! iX Konferenz
					</ext>
					Frankfurt/Main (Germany)
				</dd>
				<dd>
				<ext href="externalCitations/iXBessereSoftware2006_WebTestTutorial.pdf">Presentation <img src="images/pdficon_small.gif"/></ext> (mixed German/English)
				</dd>
			</li>

			<li>
				<dt>
					24-26.10.2006:
					<ext href="http://www.oopsla.org/2006/program/demonstrations/d03:_web_testing_made_easy.html">
						Demo: Web Testing Made Easy
					</ext>
				</dt>
				<dd>by Marc Guillemot &amp; Dierk König</dd>
				<dd>
					<ext href="http://www.oopsla.org/2006/">
						OOPSLA 2006
					</ext>
					Portland, Oregon (USA)
				</dd>
				<dd>
				<ext href="externalCitations/OOPSLA2006_WebTestAbstract.pdf">Abstract <img src="images/pdficon_small.gif"/></ext>, 
				<ext href="externalCitations/OOPSLA2006_WebTestPresentation.pdf">presentation <img src="images/pdficon_small.gif"/></ext>
				</dd>
			</li>

			<li>
				<dt>
					26.07.2006:
					<ext href="http://www.agile2006.org/program/Program#_Toc137388228">
						Agile Testing of Web Applications using WebTest
					</ext>
				</dt>
				<dd>by Paul King</dd>
				<dd>
					<ext href="http://www.agile2006.org">Agile 2006 International Conference</ext>
					Minneapolis (USA)
				</dd>
			</li>

			<li>
				<dt>
					16.03.2006:
					<ext href="http://www.swisstestingday.ch/de/programm.php">
						Automatisiertes Testen von Webapplikationen mit WebTest
					</ext>
					(German)
				</dt>
				<dd>by Benjamin Feiermann</dd>
				<dd>
					<ext href="http://www.swisstestingday.ch">Swiss Testing Day 2006</ext>
					Zürich (Switzerland)
				</dd>
			</li>

			<li>
				<dt>
					14.05.2003:
					<ext href="http://it-republik.de/konferenzen/rueckblick/jaxenter/jax2003/psecom,id,60,nodeid,2,_language,de.html">
						Funktionaler Test mit HttpUnit und WebTest
					</ext>
					(German)
				</dt>
				<dd>by Peter Roßbach &amp; Michael Kloss</dd>
				<dd>
					<ext href="http://it-republik.de/konferenzen/rueckblick/jaxenter/jax2003/psecom,id,35,nodeid,35,_language,de.html">JAX 2003</ext>
					Frankfurt am Main (Germany)
				</dd>
			</li>

		</dl>
	</section>

	<section title="Book References">
		<dl>
			<li>
				<dt>
					<ext href="http://www.oreilly.de/catalog/agileentwger/">Agile Java-Entwicklung in der Praxis</ext>
				</dt>
				<dd>Michael Hüttermann. <ext href="http://www.oreilly.de">O'Reilly</ext>, 2007.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://www.apress.com/book/bookDisplay.html?bID=10205">The Definitive Guide to Grails</ext>
				</dt>
				<dd>Graeme Rocher. <ext href="http://www.apress.com">Apress</ext>, 2006.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://www.springer.com/3-540-26277-6">Extreme Programming and Agile Processes in Software Engineering: 6th International Conference, XP 2005</ext>
				</dt>
				<dd><ext href="http://www.springer.com">Springer</ext>, 2005.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://www.oreillynet.com/cs/gp/print/b/jakartastrutsckbk">Jakarta Struts Cookbook</ext>
				</dt>
				<dd>Bill Siggelkow. <ext href="http://www.oreillynet.com">O'Reilly</ext>, 2005.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://www.springer.com/dal/home?SGWID=1-102-22-31323239-0">Extreme Programming and Agile Processes in Software Engineering: 5th International Conference, XP 2004</ext>
				</dt>
				<dd><ext href="http://www.springer.com">Springer</ext>, 2004.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://www.sourcebeat.com/TitleAction.do?id=7">Spring Live</ext>
				</dt>
				<dd>Matt Raible. <ext href="http://www.sourcebeat.com">SourceBeat</ext>, 2004.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://books.mcgraw-hill.com/getbook.php?isbn=0072231319">Struts: The Complete Reference</ext>
				</dt>
				<dd>James Holmes. <ext href="http://books.mcgraw-hill.com/">McGraw-Hill Professional</ext>, 2004.
				</dd>
			</li>
			
			<li>
				<dt>
					<ext href="http://books.elsevier.com/us/mk/us/subindex.asp?isbn=1558608680">Unit Testing in Java: How Tests Drive the Code</ext>
				</dt>
				<dd>Johannes Link. <ext href="http://books.elsevier.com">Morgan Kaufmann</ext>, 2003.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://www.manning.com/hatcher/">Java Development With Ant</ext>
				</dt>
				<dd>Erik Hatcher, Steve Loughran, Matthew Robinson, Pavel Vorobiev. <ext href="http://www.manning.com">Manning Publications</ext>, 2002.
				</dd>
			</li>
			<li>
				<dt>
					<ext href="http://www.awprofessional.com/bookstore/product.asp?isbn=0321113551&amp;rl=1">Testing Extreme Programming</ext>
				</dt>
				<dd>Lisa Crispin, Tip House. <ext href="http://www.awprofessional.com">Addison Wesley Professional</ext>, 2002.
				</dd>
			</li>
		</dl>
	</section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/release.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" [ <!ENTITY site SYSTEM "WebTestSite.xml"> ] >
<manpage siteid="Release">

    &site;

    <!-- TODO: improve, add a section on the release policy of WebTest, ... -->
    
    <head title="Release">
        <b>This page outlines how to wrap-up a WebTest release.
        </b>
    </head>
    <section title="Select a Build">
        <b>Select a succesful build, and fetch all its artefacts (build.zip, doc.zip, src.zip, ...).</b>
    </section>
    <section title="Preparation work">
        <b>Following tasks have to be accomplished in Jira:</b>
        <b>First, identify, close and assign to the release project all issues that belong to the project.
            Since this will be used for the release note, consider only the issues that have been fixed,
            and do not the rejected issues (invalid, ...).</b>
        <b>Then, mark the project as
            <em>released</em>
            in jira.
        </b>
        <b>Let jira generate the release note for the project, and saves it locally.
            It may be necessary to correct the formatting, in particular when the subject line contains webtest step
            names.</b>
    </section>

    <section title="Release">
        <b>Check in subversion module
            <ext href="https://svn.canoo.com/trunk/webtest-releases/">webtest-releases</ext>
            all the artefacts, the release note and a small read-me file.
        </b>
    </section>
    <section title="Website">
        <b>Once the release is commited, publish it on the website, on the
            <em>download</em>
            page and in the
            <em>news</em>
            column.
        </b>
        <b>Further, adapt the project reference used in the
            <em>changeLog</em>
            to the new jira project.
        </b>
    </section>

</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/repository.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd"
        [
                <!ENTITY site SYSTEM "WebTestSite.xml">
                ]
        >
<manpage siteid="Repository">

    &site;

    <head title="Repository">
        <b>This page describes the directory layout in svn.</b>
    </head>

    <section title="Directory Layout">
        <b>The layout of WebTest in svn does not follow the usual directory layout, but follows this set-up:</b>
        <dl>
            <li>
                <dt>
                    <ext href="https://svn.canoo.com/trunk/webtest">/trunk/webtest</ext>
                </dt>
                <dd>is the the head of the development;</dd>
            </li>
            <li>
                <dt>
                    <ext href="https://svn.canoo.com/versions/webtest">/versions/webtest</ext>
                </dt>
                <dd>contains the successive builds of WebTest;</dd>
            </li>
            <li>
                <dt>
                    <ext href="https://svn.canoo.com/releases/webtest">/releases/webtest</ext>
                </dt>
                <dd>contains the successive releases of WebTest.</dd>
            </li>
        </dl>
    </section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/acknowledgments.xml
<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd"
        [
                <!ENTITY site             SYSTEM "WebTestSite.xml">
                ]
        >

<manpage siteid="Acknowledgments">

    &site;

    <head title="Acknowledgments">

    </head>

    <section title="Contributors and Authors">
        <b>Thanks to</b>
        <dl>
            <li>
                <dt>Carsten Seibert,
                    <key>seiberTEC</key>
                </dt>
                <dd>for his excellent development work.</dd>
            </li>
            <li>
                <dt>Etienne Studer,
                    <key>canoo</key>
                </dt>
                <dd>for contributing the PDF test steps.</dd>
            </li>
            <li>
                <dt>Marcel R&#xfc;edi,
                    <key>canoo</key>
                </dt>
                <dd>for patching
                    <key>httpunit</key>
                    for use with HTTPS and ENTRUST.
                </dd>
            </li>
            <li>
                <dt>Marc Guillemot,</dt>
                <dd>for numerous contributions.</dd>
            </li>
            <li>
                <dt>Paul King,</dt>
                <dd>for numerous contributions.</dd>
            </li>
            <li>
                <dt>Denis N. Antonioli
                    <key>canoo</key>
                </dt>
                <dd>for numerous contributions.</dd>
            </li>
            <li>
                <dt>Rob Nielsen,</dt>
                <dd>for the Excel steps.</dd>
            </li>
            <li>
                <dt>Stefan Ruff,</dt>
                <dd>for providing and excellent stylesheet and other contributions on the mailinglist.</dd>
            </li>
            <li>
                <dt>Matt Raible,</dt>
                <dd>for his Sleep task and work on the mailinglist.</dd>
            </li>
            <li>
                <dt>Richard Hill,</dt>
                <dd>for the first version of the Sleep task.</dd>
            </li>
            <li>
                <dt>Christopher Painter-Wakefield,</dt>
                <dd>for his help on several issues.</dd>
            </li>
            <li>
                <dt>Aatish Arora,</dt>
                <dd>for his support on the mailinglist and providing patches for clickbutton.</dd>
            </li>
            <li>
                <dt>Siegfried Goeschl</dt>
                <dd>for providing the Maven plugin.</dd>
            </li>
            <li>
                <dt>Walter Rumsby</dt>
                <dd>for introducing StoreXPath.</dd>
            </li>
            <li>
                <dt>Torben Tretau</dt>
                <dd>for introducing FollowFrame.</dd>
            </li>
            <li>
                <dt>Ben Cox</dt>
                <dd>for his help in the
                    <key>mailingList</key>
                    .
                </dd>
            </li>
            <li>
                <dt>Erik Ostermueller</dt>
                <dd>for his care on the JavaScript issue.</dd>
            </li>
            <li>
                <dt>Charles Massey</dt>
                <dd>for submitting StoreRegexMatch.</dd>
            </li>
            <li>
                <dt>Donald Ball</dt>
                <dd>for introducing the VerifyXPath.</dd>
            </li>
            <li>
                <dt>Eric Pugh</dt>
                <dd>for his care about clean structures.</dd>
            </li>
            <li>
                <dt>Katja Schulze,
                    <key>cspb</key>
                </dt>
                <dd>for pilot using Canoo WebTest.</dd>
            </li>
            <li>
                <dt>Sara Camponovo,
                    <key>cspb</key>
                </dt>
                <dd>for relentlessly hunting bugs with Canoo WebTest.</dd>
            </li>
            <li>
                <dt>Pascal St&#xf6;ckli,
                    <key>csfs</key>
                </dt>
                <dd>for his bug reports and pilot use</dd>
            </li>
            <li>
                <dt>Hans-Dirk Walter,
                    <key>canoo</key>
                </dt>
                <dd>for starting the project.</dd>
            </li>
            <li>
                <dt>Martin Huber,
                    <key>canoo</key>
                </dt>
                <dd>for his requirements contributions.</dd>
            </li>
            <li>
                <dt>Stephan Huber,
                    <key>canoo</key>
                </dt>
                <dd>for the first complex usage scenarios.</dd>
            </li>
            <li>
                <dt>Dieter Holz,
                    <key>canoo</key>
                </dt>
                <dd>for providing feedback on the install, setup and documentation.</dd>
            </li>
            <li>
                <dt>Satish Verma</dt>
                <dd>for starting the reporting implementation.</dd>
            </li>
            <li>
                <dt>Urs-Peter H&#xe4;ss,
                    <key>canoo</key>
                </dt>
                <dd>for implementing verifyLinks.</dd>
            </li>
            <li>
                <dt>Peter Rossbach</dt>
                <dd>for providing a Apache Tomcat/4.0.2 compliant web.xml</dd>
            </li>
            <li>
                <dt>Dierk K&#xf6;nig,
                    <key>canoo</key>
                </dt>
                <dd>for writing this section.</dd>
            </li>
            <li>
                <dt>all the others that I just forgot to mention...</dt>
                <dd></dd>
            </li>
        </dl>
    </section>

    <section title="Third Party Authors">
        <b>Thanks to the authors of</b>
        <dl>
            <li>
                <dt>
                    <key>ANT</key>
                </dt>
                <dd>This product includes software developed by the
                    Apache Software Foundation (http://www.apache.org/).</dd>
            </li>
            <li>
                <dt>
                    <key>junit</key>
                </dt>
                <dd>released under the
                    <key>ibmPL</key>
                </dd>
            </li>
            <li>
                <dt>
                    <key>htmlunit</key>
                </dt>
                <dd>the "browser" used by webtest</dd>
            </li>
            <li>
                <dt>
                    <key>httpunit</key>
                </dt>
                <dd>the "browser" used by webtest before the switch to htmlunit</dd>
            </li>
            <li>
                <dt>
                    <key>jtidy</key>
                </dt>
            </li>
            <li>
                <dt>
                    <key>pdfbox</key>
                </dt>
                <dd>PDFBox is released under the BSD license (http://www.opensource.org/licenses/bsd-license.php)</dd>
            </li>
            <li>
                <dt>
                    <key>jakarta</key>
                </dt>
            </li>
        </dl>

        <b>Their license restrictions apply.</b>

    </section>

    <section title="Sponsors">
        <b>Follwing companies contributed licenses or resources:</b>
        <dl>
            <li>
                <dt>
                    <ext href="http://www.atlassian.com/">Atlassian Software Systems</ext>
                </dt>
                <dd>for
                    <key>Jira</key>.
                </dd>
            </li>
            <li>
                <dt>
                    <ext href="http://www.canoo.com">Canoo</ext>
                </dt>
                <dd>for the infrastructure (build server, repository)</dd>
            </li>
            <li>
                <dt>
                    <ext href="http://www.cenqua.com/">cenqua</ext>
                </dt>
                <dd>for
                    <key>CLOVER</key>
                    and for FishEye.
                </dd>
            </li>
            <li>
                <dt>
                    <ext href="http://www.jetbrains.com/">JetBrains</ext>
                </dt>
                <dd>for
                    <key>Intellij</key>
                    and for TMate.
                </dd>
            </li>
            <li>
                <dt>
                    <ext href="http://www.yourkit.com/">YourKit</ext>
                </dt>
                <dd>for YourKit Java Profiler.
                </dd>
            </li>
            <li>
                <dt>
                    <ext href="http://www.denic.de/">DENIC eG</ext>
                </dt>
                <dd>for upgrading WebTest to Ant 1.8.4.
                </dd>
            </li>
        </dl>
    </section>
</manpage>

=== i068096/Canoo-WebTest/doc/info/manual/support.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE manpage SYSTEM "manpage.dtd" 
[
	<!ENTITY site SYSTEM "WebTestSite.xml">
]
>

<manpage siteid="Support">

	&site;

	<section title="Online documentation">
		<b>
		The online documentation contains a lot of information about WebTest with numerous examples. 
		The documentation of the steps is generated directly from the Java sources and therefore always up to date.
		</b>
		<b>
		Additionally you can look at WebTest's <pageref name="Self Test Report"/> to see how steps are used.
		</b>
	</section>

	<section title="Mailing list">
		WebTest's <pageref name="Mailing list"/> is the right place for all questions concerning WebTest. 
		Most of the time you will get a very helpful answer within a short time.
	</section>
	
	<section title="Commercial support">
		<b>Nearly every qualified Java developer with web knowledge should be able
		to understand how WebTest works within a short time and could be able to use and customize it as he/she needs.
		</b>
		<b>Nevertheless the best commercial support for WebTest is surely the one provided by the people behind WebTest.
		With many years of experience in efficient web testing automation, they are the ideal source for the success of your
		WebTest projects.
		</b>
		<b>
		Have a look at <ext href="http://www.efficient-webtesting.com/">http://www.efficient-webtesting.com/</ext> if you're
		looking for training, consulting or support with guaranteed response time.
		</b>
	</section>
</manpage>
